package com.m.d.common.entity.model;

import com.m.d.common.util.msgutil.MessageKit;
import com.m.d.common.util.core.JModel;
import java.math.BigInteger;

import com.jfinal.plugin.activerecord.IBean;
import com.jfinal.plugin.ehcache.CacheKit;
import com.jfinal.plugin.ehcache.IDataLoader;

/**
 *  Auto generated by JPress, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseMFrends<M extends BaseMFrends<M>> extends JModel<M> implements IBean {

	public static final String CACHE_NAME = "frends";
	public static final String METADATA_TYPE = "frends";

	public static final String ACTION_ADD = "frends:add";
	public static final String ACTION_DELETE = "frends:delete";
	public static final String ACTION_UPDATE = "frends:update";

	public void removeCache(Object key){
		if(key == null) return;
		CacheKit.remove(CACHE_NAME, key);
	}

	public void putCache(Object key,Object value){
		CacheKit.put(CACHE_NAME, key, value);
	}

	public M getCache(Object key){
		return CacheKit.get(CACHE_NAME, key);
	}

	public M getCache(Object key,IDataLoader dataloader){
		return CacheKit.get(CACHE_NAME, key, dataloader);
	}

	@Override
	public boolean equals(Object o) {
		if(o == null){ return false; }
		if(!(o instanceof BaseMFrends<?>)){return false;}

		BaseMFrends<?> m = (BaseMFrends<?>) o;
		if(m.getId() == null){return false;}

		return m.getId().compareTo(this.getId()) == 0;
	}

	@Override
	public boolean save() {
		boolean saved = super.save();
		if (saved) { MessageKit.sendMessage(ACTION_ADD, this); }
		return saved;
	}

	@Override
	public boolean delete() {
		boolean deleted = super.delete();
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean deleteById(Object idValue) {
		boolean deleted = super.deleteById(idValue);
		if (deleted) { MessageKit.sendMessage(ACTION_DELETE, this); }
		return deleted;
	}

	@Override
	public boolean update() {
		boolean update = super.update();
		if (update) { MessageKit.sendMessage(ACTION_UPDATE, this); }
		return update;
	}

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserNum(java.lang.String userNum) {
		set("user_num", userNum);
	}

	public java.lang.String getUserNum() {
		return get("user_num");
	}

	public void setFrendNum(java.lang.String frendNum) {
		set("frend_num", frendNum);
	}

	public java.lang.String getFrendNum() {
		return get("frend_num");
	}

}
