package com.m.d.common.entity;

import com.m.d.common.util.core.Table;
import com.m.d.common.entity.model.BaseMFrends;

/**
 * Generated by JPress.
 */
@Table(tableName="frends",primaryKey="id")
public class MFrends extends BaseMFrends<MFrends> {
	
}
