package com.m.d.common.entity;


import com.m.d.common.entity.model.BaseMUser;
import com.m.d.common.util.core.Table;

/**
 * Generated by JPress.
 */
@Table(tableName="user",primaryKey="id")
public class MUser extends BaseMUser<MUser> {
	
}
